// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwZpAqGgcjz4ANnhTBZU_qq5JWxxhK2Xg',
    appId: '1:696456715362:web:6f3ae4ffce57fecadc453b',
    messagingSenderId: '696456715362',
    projectId: 'traspo-70399',
    authDomain: 'traspo-70399.firebaseapp.com',
    storageBucket: 'traspo-70399.appspot.com',
    measurementId: 'G-2VYHT13VR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDTF8TvYV8-DBva4TATx1M5uH84mQoFKQ',
    appId: '1:696456715362:android:2bfaf74543ed590ddc453b',
    messagingSenderId: '696456715362',
    projectId: 'traspo-70399',
    storageBucket: 'traspo-70399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmm6pgfxK-0raHrDa1BkIucJh-RgkYj70',
    appId: '1:696456715362:ios:57aa80d8a3e82b89dc453b',
    messagingSenderId: '696456715362',
    projectId: 'traspo-70399',
    storageBucket: 'traspo-70399.appspot.com',
    iosClientId: '696456715362-7188qcarqk9pb9js58hkbl8sj0d0b2sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.transpo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmm6pgfxK-0raHrDa1BkIucJh-RgkYj70',
    appId: '1:696456715362:ios:57aa80d8a3e82b89dc453b',
    messagingSenderId: '696456715362',
    projectId: 'traspo-70399',
    storageBucket: 'traspo-70399.appspot.com',
    iosClientId: '696456715362-7188qcarqk9pb9js58hkbl8sj0d0b2sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.transpo',
  );
}
